import argparse


def get_config():
    parser = argparse.ArgumentParser(description="macpo", formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--algorithm_name", type=str, default=" ", choices=["macpo"])
    parser.add_argument("--experiment_name", type=str, default="check")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--cuda_deterministic", action="store_false", default=True)
    parser.add_argument("--n_training_threads", type=int, default=1)
    parser.add_argument("--n_rollout_threads", type=int, default=32)
    parser.add_argument("--n_eval_rollout_threads", type=int, default=1)
    parser.add_argument("--num_env_steps", type=int, default=10e6)
    parser.add_argument("--env_name", type=str, default="StarCraft2")
    parser.add_argument("--episode_length", type=int, default=200)
    parser.add_argument("--hidden_size", type=int, default=64)
    parser.add_argument("--layer_N", type=int, default=1)
    parser.add_argument("--use_ReLU", action="store_false", default=True)
    parser.add_argument("--use_feature_normalization", action="store_false", default=True)
    parser.add_argument("--use_orthogonal", action="store_false", default=True)
    parser.add_argument("--gain", type=float, default=0.01)
    parser.add_argument("--lr", type=float, default=5e-4)
    parser.add_argument("--critic_lr", type=float, default=5e-4)
    parser.add_argument("--opti_eps", type=float, default=1e-5)
    parser.add_argument("--weight_decay", type=float, default=0)
    parser.add_argument("--std_x_coef", type=float, default=1)
    parser.add_argument("--std_y_coef", type=float, default=0.5)
    parser.add_argument("--kl_threshold", type=float, default=0.01)
    parser.add_argument("--safety_bound", type=float, default=0.1)
    parser.add_argument("--ls_step", type=int, default=10)
    parser.add_argument("--EPS", type=float, default=1e-8)
    parser.add_argument("--ppo_epoch", type=int, default=15)
    parser.add_argument("--clip_param", type=float, default=0.2)
    parser.add_argument("--num_mini_batch", type=int, default=1)
    parser.add_argument("--value_loss_coef", type=float, default=1)
    parser.add_argument("--max_grad_norm", type=float, default=10.0)
    parser.add_argument("--gamma", type=float, default=0.99)
    parser.add_argument("--gae_lambda", type=float, default=0.95)
    parser.add_argument("--use_value_active_masks", action="store_false", default=True)
    parser.add_argument("--huber_delta", type=float, default=10.0)
    parser.add_argument("--save_interval", type=int, default=1)
    parser.add_argument("--keep_checkpoints", action="store_true", default=False)
    parser.add_argument("--log_interval", type=int, default=5)
    parser.add_argument("--use_eval", action="store_true", default=False)
    parser.add_argument("--done_config", type=str, default="never")
    parser.add_argument("--eval_interval", type=int, default=25)
    parser.add_argument("--eval_episodes", type=int, default=32)
    parser.add_argument("--line_search_fraction", type=float, default=0.5)
    parser.add_argument("--fraction_coef", type=float, default=0.1)
    return parser
